import test from 'node:test';
import assert from 'node:assert/strict';
import {KEYS,normalizeField,compareDocuments,number} from './rules.js';
import {keywordGate,localExtract,localClassify,makeProvider,providerStatus} from './provider.js';
import {runPipeline,reviewAction} from './pipeline.js';
import {competitionOutput,diagnostics} from './export.js';
export const text=(type,count='3',weight='22000 KG')=>`${type}\nBooking Reference: BK-200\nShipper: Oceanic Traders Ltd\nConsignee: Harbor Imports\nNotify party: Harbor Imports\nPort of loading: Singapore (SGSIN)\nPort of discharge: Los Angeles (USLAX)\nContainer count: ${count}\nGross weight: ${weight}`;
const doc=(type,count,weight,id=type)=>({id,name:type+'.txt',sha256:id,pages:[{page:1,text:text(type,count,weight),method:'native'}]});
const base=()=>({id:'email-1',emailId:'email-1',subject:'Compare SI and BL',body:'Please check the draft BL against the SI.',category:'GENERAL',classificationPending:true,attachments:[],fields:{},history:[],version:1,docs:[]});
test('keyword gate follows full HTML scope and exact token boundaries',()=>{for(const body of ['SI','BL','B/L','bills  of lading','Shipping Instructions','提单','a'.repeat(10000)+' BL'])assert.equal(keywordGate({subject:'',body}),true);for(const body of ['possible','billing','Please check the attached draft'])assert.equal(keywordGate({subject:'',body}),false)});
test('mention and quoted old requests cannot silently classify as a new check',()=>{assert.equal(localClassify({subject:'BL',body:'Please send the BL.'}).needsReview,true);assert.notEqual(localClassify({subject:'Thanks',body:'Noted.\nOn Monday wrote:\nPlease check the BL.'}).category,'BL_COMPARISON')});
test('explicit invoice questions outside the SI/BL keyword gate complete as classification only',async()=>{const provider=makeProvider({GRAFILAB_API_KEY:'test'},async()=>{throw Error('A clear invoice query should not need a paid model call')});const routed=await provider.classify({subject:'Local charges',body:'Query on invoice 5250075931: is the local charge included or billed separately?'});assert.equal(routed.category,'INVOICE_QUERY');assert.equal(routed.needsReview,false);const c=await runPipeline({...base(),subject:'Local charges',body:'Query on invoice 5250075931: is the local charge included or billed separately?'},[],{GRAFILAB_API_KEY:'test'},{fetcher:async()=>{throw Error('No paid call expected')}});assert.equal(c.pipeline.status,'complete');assert.deepEqual(c.fields,{});assert.equal(competitionOutput([c]).output['email-1'].status,'OK')});
test('route-only phase completes non-comparison mail and queues comparison mail without extraction',async()=>{const invoice=await runPipeline({...base(),subject:'Local charges',body:'Query on invoice 5250075931: is the local charge included or billed separately?'},[],{},{routeOnly:true});assert.equal(invoice.category,'INVOICE_QUERY');assert.equal(invoice.pipeline.status,'complete');assert.deepEqual(invoice.fields,{});const comparison=await runPipeline(base(),[],{},{routeOnly:true});assert.equal(comparison.category,'BL_COMPARISON');assert.equal(comparison.pipeline.status,'routed');assert.equal(Object.values(comparison.fields).every(field=>field.comparison===null),true);assert.deepEqual(comparison.docs,[])});
test('numeric grammar, units, precise decimal arithmetic and no guessed locale',()=>{for(const [raw,p,value] of [['22 MT','unset','22000'],['22MT','unset','22000'],['22 M/T','unset','22000'],['22 KGS','unset','22'],['22,000.00 KGS','en_comma','22000'],['TWENTY-TWO METRIC TONS','unset','22000'],['22.000 MT','en_comma','22000'],['0 KG','unset','0'],['0.001 MT','en_comma','1']])assert.equal(normalizeField('gross_weight_kg',raw,p).value,value,raw);for(const raw of ['22.000 MT','22,000 KG','22 TONS','22 MT / 23 MT','TWENTYISH METRIC TONS','-22 KG'])assert.equal(normalizeField('gross_weight_kg',raw).ok,false,raw);assert.equal(normalizeField('gross_weight_kg','22,00.00 KG','en_comma').ok,false);assert.equal(normalizeField('gross_weight_kg','22000').kind,'MISSING');assert.equal(normalizeField('gross_weight_kg','N/A').kind,'MISSING');assert.equal(number('9007199254740993').value,'9007199254740993')});
test('container counts preserve count instead of container dimensions',()=>{assert.equal(normalizeField('container_count',"6 × 40'HC").value,'6');for(const x of ['0','-1','2.5','40 cartons'])assert.equal(normalizeField('container_count',x).ok,false)});
test('ports accept documented country and terminal detail without accepting conflicting codes',()=>{assert.equal(normalizeField('port_of_loading','Port Klang (MYPKG)').value,'MYPKG');assert.equal(normalizeField('port_of_loading','PORT KLANG (WESTPORT), MALAYSIA (MYPKG)').value,'MYPKG');assert.equal(normalizeField('port_of_discharge','CALLAO, PERU (PECLL)').value,'PECLL');for(const x of ['Port Klang (USLAX)','New Mystery Harbor','Portland'])assert.equal(normalizeField('port_of_loading',x).ok,false)});
test('real native text goes through classification, independent extraction and rules',async()=>{const c=await runPipeline(base(),[doc('SHIPPING INSTRUCTIONS'),doc('BILL OF LADING')]);assert.equal(c.pipeline.status,'complete');assert.equal(Object.values(c.fields).filter(f=>f.comparison==='MATCH').length,7);assert.equal(c.pipeline.rereads,0);assert.equal(c.fields.shipper.evidence.si.page,1)});
test('different value and missing value coexist; verification never clears either',async()=>{let c=await runPipeline(base(),[doc('SHIPPING INSTRUCTIONS','3','N/A'),doc('BILL OF LADING','4')]);assert.equal(c.fields.container_count.comparison,'MISMATCH');assert.equal(c.fields.gross_weight_kg.kind,'MISSING');c=reviewAction(c,'verify',{field:'container_count'});assert.equal(c.fields.container_count.comparison,'MISMATCH');assert.equal(c.fields.gross_weight_kg.comparison,null)});
test('a missing extraction location is unreadable, not a made-up missing fact',async()=>{const a=doc('SHIPPING INSTRUCTIONS');a.pages[0].text=a.pages[0].text.replace('Gross weight: 22000 KG','');const c=await runPipeline(base(),[a,doc('BILL OF LADING')]);assert.equal(c.fields.gross_weight_kg.kind,'UNREADABLE')});
test('multiple revisions, booking conflicts and misleading filenames do not auto-pair',async()=>{let c=await runPipeline(base(),[doc('SHIPPING INSTRUCTIONS'),doc('SHIPPING INSTRUCTIONS','4',undefined,'revision'),doc('BILL OF LADING')]);assert.equal(c.pairIssue,true);const a=doc('BILL OF LADING');a.pages[0].text=a.pages[0].text.replace('BK-200','OTHER');c=await runPipeline(base(),[doc('SHIPPING INSTRUCTIONS'),a]);assert.equal(c.pairIssue,true);const fake={id:'invoice',name:'BL.pdf',pages:[{page:1,text:'INVOICE\nGross weight: 22000 KG',method:'native'}]};c=await runPipeline(base(),[doc('SHIPPING INSTRUCTIONS'),fake]);assert.equal(c.docIssue,'wrong_type')});
test('source corrections and semantic manual decisions retain an audit trail',async()=>{let c=await runPipeline(base(),[doc('SHIPPING INSTRUCTIONS',undefined,'22.000 MT'),doc('BILL OF LADING')]);c=reviewAction(c,'resolve',{field:'gross_weight_kg',siValue:'22.000 MT',blValue:'22000 KG',decision:'MATCH',note:'SI page 1: sender specification uses a decimal point.'});assert.equal(c.fields.gross_weight_kg.manual,true);assert.equal(c.sourceVersions.length>0,true)});
test('API output schema rejects hallucinated structure and prompt data stays untrusted',async()=>{const env={AI_API_KEY:'test',AI_BASE_URL:'https://test.example/v1',AI_MODEL:'test'};const p=makeProvider(env,async()=>Response.json({choices:[{message:{content:'{"madeUp":true}'}}]}));await assert.rejects(()=>p.extract(doc('SHIPPING INSTRUCTIONS')),/contract/)});
test('Grafilab uses the account console endpoint and the selected vision model only for images',async()=>{
 const env={GRAFILAB_API_KEY:'test',GRAFILAB_MODEL:'gemini/gemini-3.5-flash-lite',GRAFILAB_VISION_MODEL:'gemini/gemini-3.6-flash'};
 const seen=[],fetcher=async(url,opts)=>{seen.push({url,model:JSON.parse(opts.body).model});const result=localExtract(doc('SHIPPING INSTRUCTIONS'));delete result.provider;return Response.json({choices:[{message:{content:JSON.stringify(result)}}]})};
 const p=makeProvider(env,fetcher);await p.extract(doc('SHIPPING INSTRUCTIONS'));await p.reread(doc('SHIPPING INSTRUCTIONS'),['shipper'],'data:image/png;base64,dGVzdA==');
 assert.deepEqual(seen,[{url:'https://llm.grafilab.ai/v1/chat/completions',model:env.GRAFILAB_MODEL},{url:'https://llm.grafilab.ai/v1/chat/completions',model:env.GRAFILAB_VISION_MODEL}]);
});
test('Grafilab can retry without JSON mode when a model rejects that request option',async()=>{
 const formats=[],fetcher=async(_url,opts)=>{const body=JSON.parse(opts.body);formats.push(!!body.response_format);if(body.response_format)return new Response('',{status:400});const result=localExtract(doc('SHIPPING INSTRUCTIONS'));delete result.provider;return Response.json({choices:[{message:{content:JSON.stringify(result)}}]})};
 const provider=makeProvider({GRAFILAB_API_KEY:'test'},fetcher);assert.equal((await provider.extract(doc('SHIPPING INSTRUCTIONS'))).type,'SI');assert.deepEqual(formats,[true,false]);
});
test('native document labels recover two independent entity differences from an incomplete AI extraction',async()=>{
 const si={id:'si',name:'si.txt',pages:[{page:1,method:'native',text:'SHIPPING INSTRUCTION\nBooking Ref: BK-200\nShipper: APRIL FAR EAST\nConsignee (Non-Negotiable): EAST BRIGHT FZ-LLC\nNotify: EAST BRIGHT FZ-LLC'}]};
 const bl={id:'bl',name:'bl.txt',pages:[{page:1,method:'native',text:'BILL OF LADING (DRAFT)\nBooking Ref: BK-200\nShipper: APRIL FAR EAST\nTo the Order of: UAB NOVAKOPA\nNotify Party: UAB NOVAKOPA'}]};
 const provider=makeProvider({GRAFILAB_API_KEY:'test'},async(_url,opts)=>{const input=JSON.parse(JSON.parse(opts.body).messages[1].content[0].text),result=localExtract(input);for(const key of ['consignee','notify_party'])result.fields[key]={raw:null,quote:'',page:1,status:'MISSING'};if(input.name==='bl.txt'){result.fields.shipper={raw:'APRIL FAR EAST\nTo the Order of: UAB NOVAKOPA',quote:'Shipper: APRIL FAR EAST\nTo the Order of: UAB NOVAKOPA',page:1,status:'OK'}}delete result.provider;return Response.json({choices:[{message:{content:JSON.stringify(result)}}]})});
 const a={...si,...await provider.extract(si)},b={...bl,...await provider.extract(bl)};
 assert.deepEqual(a.recoveredFields,['consignee','notify_party']);assert.deepEqual(b.recoveredFields,['shipper','consignee','notify_party']);
 const checked=compareDocuments(a,b);assert.equal(checked.shipper.comparison,'MATCH');assert.equal(checked.consignee.comparison,'MISMATCH');assert.equal(checked.notify_party.comparison,'MISMATCH');assert.equal(a.booking,b.booking);
});
test('Jev routes email only, with low confidence or weak comparison intent sent to review',async()=>{
 const env={TYPESAFE_API_KEY:'test'};assert.deepEqual(providerStatus(env),{mode:'local-rules',model:null,visionModel:null,ocrModel:null,routing:'jev',extraction:'local-rules'});
 const calls=[],fetcher=async(url,opts)=>{calls.push({url,body:JSON.parse(opts.body)});return Response.json({answers:{category:{choice:'BL_COMPARISON',confidence:0.93},compare_intent:{noul:0.92}}})};
 const p=makeProvider(env,fetcher),email={subject:'Please check our draft BL',body:'Attached SI and BL. Please compare them.'};
 const routed=await p.classify(email);assert.equal(routed.category,'BL_COMPARISON');assert.equal(routed.needsReview,false);assert.equal(routed.provider,'jev');assert.equal(calls[0].url,'https://api.typesafe.ai/v1/systemone');assert.equal(calls[0].body.model,'jev-1.13.0');
 const low=makeProvider(env,async()=>Response.json({answers:{category:{choice:'BL_COMPARISON',confidence:0.93},compare_intent:{noul:0.3}}}));assert.equal((await low.classify(email)).needsReview,true);
});
test('low-confidence scanned page uses Grafilab OCR once without a redundant visual reread',async()=>{
 const env={GRAFILAB_API_KEY:'test',GRAFILAB_MODEL:'gemini/gemini-3.5-flash-lite',GRAFILAB_OCR_MODEL:'grafilab/glm-ocr'};
 const si=doc('SHIPPING INSTRUCTIONS'),bl=doc('BILL OF LADING');si.pages[0]={page:1,text:'SHIPPING INSTRUCTIONS\nBooking Reference: BK-200\nShipper: ?\nGross weight: ??',method:'ocr',confidence:42,imageId:'si-page'};
 let ocrCalls=0,extractCalls=0;
 const fetcher=async(url,opts)=>{const request=JSON.parse(opts.body);
  if(request.model==='grafilab/glm-ocr'){ocrCalls++;return Response.json({choices:[{message:{content:text('SHIPPING INSTRUCTIONS')}}]})}
  if(request.messages[0].content.includes('BL_COMPARISON requires'))return Response.json({choices:[{message:{content:JSON.stringify({category:'BL_COMPARISON',quote:'Please check the draft BL against the SI.',reason:'Explicit request',needsReview:false})}}]});
  extractCalls++;const source=JSON.parse(request.messages[1].content[0].text),result=localExtract(request.messages[1].content.some(c=>c.type==='image_url')?doc('SHIPPING INSTRUCTIONS'):source);delete result.provider;
  return Response.json({choices:[{message:{content:JSON.stringify(result)}}]})};
 const opts={fetcher,getPageImage:async()=> 'data:image/png;base64,dGVzdA=='};
 let checked=await runPipeline(base(),[si,bl],env,opts);assert.equal(checked.pipeline.status,'complete');assert.equal(checked.docs[0].pages[0].ocrEngine,'grafilab/glm-ocr');assert.match(checked.docs[0].pages[0].browserOcrText,/Shipper: \?/);assert.equal(ocrCalls,1);assert.equal(checked.pipeline.rereads,0);assert.equal(extractCalls,2);
 checked=await runPipeline(checked,[si,bl],env,opts);assert.equal(checked.pipeline.status,'complete');assert.equal(ocrCalls,1);assert.equal(extractCalls,2);
});
test('official export reports a known difference while retaining unresolved fields internally',async()=>{const c=await runPipeline(base(),[doc('SHIPPING INSTRUCTIONS','3','N/A'),doc('BILL OF LADING','4')]);const result=competitionOutput([c]);assert.equal(result.ready,true);assert.deepEqual(result.output['email-1'],{category:'BL_COMPARISON',status:'MISMATCH',review_reason:null,has_defect:true,defect_fields:['container_count']});assert.equal(c.fields.gross_weight_kg.kind,'MISSING');assert.deepEqual(competitionOutput([{...c,category:'GENERAL'}]).output['email-1'],{category:'GENERAL',status:'OK',review_reason:null,has_defect:false,defect_fields:[]});assert.equal(diagnostics([c]).attempted,1)});
test('requesting a draft BL without attachments is classification only, while an explicit comparison still needs sources',async()=>{const request={...base(),subject:'Draft BL request',body:'Please assist to send the draft BL for BK-200 for checking asap.',classification:{category:'BL_COMPARISON',quote:'Please assist to send the draft BL',reason:'Request to send the draft',needsReview:false,provider:'human'}};const classified=await runPipeline(request,[],{},{keepCategory:true});const routed=await runPipeline(request,[],{},{keepCategory:true,routeOnly:true});assert.equal(routed.classificationOnly,true);assert.equal(routed.pipeline.status,'complete');assert.deepEqual(competitionOutput([routed]).output,competitionOutput([classified]).output);assert.equal(classified.classificationOnly,true);assert.deepEqual(classified.fields,{});assert.equal(classified.pipeline.status,'complete');assert.deepEqual(competitionOutput([classified]).output['email-1'],{category:'BL_COMPARISON',status:'OK',review_reason:null,has_defect:false,defect_fields:[]});const compare={...request,body:'Please compare the SI and draft BL; attachments were dropped.'};const unpaired=await runPipeline(compare,[],{},{keepCategory:true});assert.equal(unpaired.classificationOnly,false);assert.equal(unpaired.docIssue,'missing_si');assert.equal(competitionOutput([unpaired]).output['email-1'].status,'NEEDS_REVIEW')});
test('entity scope preserves one-sided addresses and blocks conflicting addresses',async()=>{
 const si=doc('SHIPPING INSTRUCTIONS'),bl=doc('BILL OF LADING');si.pages[0].text=si.pages[0].text.replace('Oceanic Traders Ltd','Oceanic Traders Ltd\n88 Industrial Road');let c=await runPipeline(base(),[si,bl]);assert.equal(c.fields.shipper.comparison,'MATCH');bl.pages[0].text=bl.pages[0].text.replace('Oceanic Traders Ltd','Oceanic Traders Ltd\n99 Harbour Road');c=await runPipeline(base(),[si,bl]);assert.equal(c.fields.shipper.comparison,'MATCH');assert.equal(c.fields.shipper.scope_warning,'address_conflict');assert.equal(c.pipeline.status,'review');assert.equal(competitionOutput([c]).ready,false)
});
test('company headings stay outside values, but an in-value order relationship remains material',()=>{
 const si=doc('SHIPPING INSTRUCTIONS'),bl=doc('BILL OF LADING');
 si.pages[0].text=si.pages[0].text.replace('Shipper:','Shipper/Exporter:');
 bl.pages[0].text=bl.pages[0].text.replace('Shipper:','Shipper (Principal or Seller):').replace('Consignee:','Consignee (Non-Negotiable):');
 const a={...si,...localExtract(si)},b={...bl,...localExtract(bl)};
 a.fields.shipper.entity.qualifier='Exporter';b.fields.shipper.entity.qualifier='Principal or Seller';b.fields.consignee.entity.qualifier='Non-Negotiable';
 let checked=compareDocuments(a,b);assert.equal(checked.shipper.comparison,'MATCH');assert.equal(checked.consignee.comparison,'MATCH');
 bl.pages[0].text=bl.pages[0].text.replace('Consignee (Non-Negotiable):','To the Order of:');const ordered={...bl,...localExtract(bl)};
 checked=compareDocuments(a,ordered);assert.equal(checked.consignee.comparison,'MATCH');
 bl.pages[0].text=bl.pages[0].text.replace('To the Order of: Harbor Imports','Consignee: TO THE ORDER OF Harbor Imports');
 checked=compareDocuments(a,{...bl,...localExtract(bl)});assert.equal(checked.consignee.comparison,'MISMATCH');
});
test('visual recovery is one targeted round, independent and cached',async()=>{
 let visualCalls=0,extractCalls=0;const env={AI_API_KEY:'test',AI_BASE_URL:'https://test.example/v1',AI_MODEL:'model-1'};
 const si=doc('SHIPPING INSTRUCTIONS'),bl=doc('BILL OF LADING');si.pages[0].imageId='raster';si.pages[0].method='ocr';si.pages[0].confidence=95;
 const fetcher=async(url,opts)=>{const data=JSON.parse(opts.body),system=data.messages[0].content,input=JSON.parse(data.messages[1].content[0].text);let result;
  if(system.includes('BL_COMPARISON requires'))result={category:'BL_COMPARISON',quote:'Please check the draft BL against the SI.',reason:'Explicit request',needsReview:false};
  else {const visual=data.messages[1].content.some(c=>c.type==='image_url');result=localExtract(visual?si:input);delete result.provider;if(visual){visualCalls++;assert.deepEqual(input,{pages:[{page:1}]})}else {extractCalls++;if(input.name===si.name)result.fields.gross_weight_kg={raw:'misread',quote:'misread',page:1,status:'OK'}}}
  return Response.json({choices:[{message:{content:JSON.stringify(result)}}]})};
 let c=await runPipeline(base(),[si,bl],env,{fetcher,getPageImage:async()=> 'data:image/png;base64,dGVzdA=='});assert.equal(visualCalls,1);assert.equal(extractCalls,2);assert.equal(c.fields.gross_weight_kg.comparison,'MATCH');
 c=await runPipeline(c,[si,bl],env,{fetcher,getPageImage:async()=> 'data:image/png;base64,dGVzdA=='});assert.equal(visualCalls,1);assert.equal(extractCalls,2)
});
test('net-weight quotes cannot validate a gross-weight extraction',()=>{const si=doc('SHIPPING INSTRUCTIONS'),bl=doc('BILL OF LADING');const a={...si,...localExtract(si)},b={...bl,...localExtract(bl)};a.fields.gross_weight_kg.quote='Net weight: 22000 KG';a.pages[0].text+='\nNet weight: 22000 KG';assert.equal(compareDocuments(a,b).gross_weight_kg.comparison,null)});
test('rechecking unchanged evidence retains reviewed differences',async()=>{const docs=[doc('SHIPPING INSTRUCTIONS'),doc('BILL OF LADING','4')];let c=await runPipeline(base(),docs);c=reviewAction(c,'verify',{field:'container_count'});c=await runPipeline(c,docs);assert.equal(c.fields.container_count.verified,true);assert.equal(c.fields.container_count.comparison,'MISMATCH')});
