import test from 'node:test';
import assert from 'node:assert/strict';
import {KEYS,normalizeField,compareDocuments,number} from './rules.js';
import {keywordGate,localExtract,localClassify,makeProvider} from './provider.js';
import {runPipeline,reviewAction} from './pipeline.js';
import {competitionOutput,diagnostics} from './export.js';
export const text=(type,count='3',weight='22000 KG')=>`${type}\nBooking Reference: BK-200\nShipper: Oceanic Traders Ltd\nConsignee: Harbor Imports\nNotify party: Harbor Imports\nPort of loading: Singapore (SGSIN)\nPort of discharge: Los Angeles (USLAX)\nContainer count: ${count}\nGross weight: ${weight}`;
const doc=(type,count,weight,id=type)=>({id,name:type+'.txt',sha256:id,pages:[{page:1,text:text(type,count,weight),method:'native'}]});
const base=()=>({id:'email-1',emailId:'email-1',subject:'Compare SI and BL',body:'Please check the draft BL against the SI.',category:'GENERAL',classificationPending:true,attachments:[],fields:{},history:[],version:1,docs:[]});
test('keyword gate follows full HTML scope and exact token boundaries',()=>{for(const body of ['SI','BL','B/L','bills  of lading','Shipping Instructions','提单','a'.repeat(10000)+' BL'])assert.equal(keywordGate({subject:'',body}),true);for(const body of ['possible','billing','Please check the attached draft'])assert.equal(keywordGate({subject:'',body}),false)});
test('mention and quoted old requests cannot silently classify as a new check',()=>{assert.equal(localClassify({subject:'BL',body:'Please send the BL.'}).needsReview,true);assert.notEqual(localClassify({subject:'Thanks',body:'Noted.\nOn Monday wrote:\nPlease check the BL.'}).category,'BL_COMPARISON')});
test('numeric grammar, units, precise decimal arithmetic and no guessed locale',()=>{for(const [raw,p,value] of [['22 MT','unset','22000'],['22MT','unset','22000'],['22 M/T','unset','22000'],['22 KGS','unset','22'],['22,000.00 KGS','en_comma','22000'],['TWENTY-TWO METRIC TONS','unset','22000'],['22.000 MT','en_comma','22000'],['0 KG','unset','0'],['0.001 MT','en_comma','1']])assert.equal(normalizeField('gross_weight_kg',raw,p).value,value,raw);for(const raw of ['22.000 MT','22,000 KG','22 TONS','22 MT / 23 MT','TWENTYISH METRIC TONS','-22 KG'])assert.equal(normalizeField('gross_weight_kg',raw).ok,false,raw);assert.equal(normalizeField('gross_weight_kg','22,00.00 KG','en_comma').ok,false);assert.equal(normalizeField('gross_weight_kg','22000').kind,'MISSING');assert.equal(normalizeField('gross_weight_kg','N/A').kind,'MISSING');assert.equal(number('9007199254740993').value,'9007199254740993')});
test('container counts preserve count instead of container dimensions',()=>{assert.equal(normalizeField('container_count',"6 × 40'HC").value,'6');for(const x of ['0','-1','2.5','40 cartons'])assert.equal(normalizeField('container_count',x).ok,false)});
test('ports require finite unique mapping and reject name-code conflicts',()=>{assert.equal(normalizeField('port_of_loading','Port Klang (MYPKG)').value,'MYPKG');for(const x of ['Port Klang (USLAX)','New Mystery Harbor','Portland'])assert.equal(normalizeField('port_of_loading',x).ok,false)});
test('real native text goes through classification, independent extraction and rules',async()=>{const c=await runPipeline(base(),[doc('SHIPPING INSTRUCTIONS'),doc('BILL OF LADING')]);assert.equal(c.pipeline.status,'complete');assert.equal(Object.values(c.fields).filter(f=>f.comparison==='MATCH').length,7);assert.equal(c.pipeline.rereads,0);assert.equal(c.fields.shipper.evidence.si.page,1)});
test('different value and missing value coexist; verification never clears either',async()=>{let c=await runPipeline(base(),[doc('SHIPPING INSTRUCTIONS','3','N/A'),doc('BILL OF LADING','4')]);assert.equal(c.fields.container_count.comparison,'MISMATCH');assert.equal(c.fields.gross_weight_kg.kind,'MISSING');c=reviewAction(c,'verify',{field:'container_count'});assert.equal(c.fields.container_count.comparison,'MISMATCH');assert.equal(c.fields.gross_weight_kg.comparison,null)});
test('a missing extraction location is unreadable, not a made-up missing fact',async()=>{const a=doc('SHIPPING INSTRUCTIONS');a.pages[0].text=a.pages[0].text.replace('Gross weight: 22000 KG','');const c=await runPipeline(base(),[a,doc('BILL OF LADING')]);assert.equal(c.fields.gross_weight_kg.kind,'UNREADABLE')});
test('multiple revisions, booking conflicts and misleading filenames do not auto-pair',async()=>{let c=await runPipeline(base(),[doc('SHIPPING INSTRUCTIONS'),doc('SHIPPING INSTRUCTIONS','4',undefined,'revision'),doc('BILL OF LADING')]);assert.equal(c.pairIssue,true);const a=doc('BILL OF LADING');a.pages[0].text=a.pages[0].text.replace('BK-200','OTHER');c=await runPipeline(base(),[doc('SHIPPING INSTRUCTIONS'),a]);assert.equal(c.pairIssue,true);const fake={id:'invoice',name:'BL.pdf',pages:[{page:1,text:'INVOICE\nGross weight: 22000 KG',method:'native'}]};c=await runPipeline(base(),[doc('SHIPPING INSTRUCTIONS'),fake]);assert.equal(c.docIssue,'wrong_type')});
test('source corrections and semantic manual decisions retain an audit trail',async()=>{let c=await runPipeline(base(),[doc('SHIPPING INSTRUCTIONS',undefined,'22.000 MT'),doc('BILL OF LADING')]);c=reviewAction(c,'resolve',{field:'gross_weight_kg',siValue:'22.000 MT',blValue:'22000 KG',decision:'MATCH',note:'SI page 1: sender specification uses a decimal point.'});assert.equal(c.fields.gross_weight_kg.manual,true);assert.equal(c.sourceVersions.length>0,true)});
test('API output schema rejects hallucinated structure and prompt data stays untrusted',async()=>{const env={AI_API_KEY:'test',AI_BASE_URL:'https://test.example/v1',AI_MODEL:'test'};const p=makeProvider(env,async()=>Response.json({choices:[{message:{content:'{"madeUp":true}'}}]}));await assert.rejects(()=>p.extract(doc('SHIPPING INSTRUCTIONS')),/contract/)});
test('official export reports a known difference while retaining unresolved fields internally',async()=>{const c=await runPipeline(base(),[doc('SHIPPING INSTRUCTIONS','3','N/A'),doc('BILL OF LADING','4')]);const result=competitionOutput([c]);assert.equal(result.ready,true);assert.deepEqual(result.output['email-1'],{category:'BL_COMPARISON',status:'MISMATCH',review_reason:null,has_defect:true,defect_fields:['container_count']});assert.equal(c.fields.gross_weight_kg.kind,'MISSING');assert.equal(competitionOutput([{...c,category:'GENERAL'}]).ready,false);assert.equal(diagnostics([c]).attempted,1)});
test('entity scope preserves one-sided addresses and blocks conflicting addresses',async()=>{
 const si=doc('SHIPPING INSTRUCTIONS'),bl=doc('BILL OF LADING');si.pages[0].text=si.pages[0].text.replace('Oceanic Traders Ltd','Oceanic Traders Ltd\n88 Industrial Road');let c=await runPipeline(base(),[si,bl]);assert.equal(c.fields.shipper.comparison,'MATCH');bl.pages[0].text=bl.pages[0].text.replace('Oceanic Traders Ltd','Oceanic Traders Ltd\n99 Harbour Road');c=await runPipeline(base(),[si,bl]);assert.equal(c.fields.shipper.comparison,'MATCH');assert.equal(c.fields.shipper.scope_warning,'address_conflict');assert.equal(c.pipeline.status,'review');assert.equal(competitionOutput([c]).ready,false)
});
test('visual recovery is one targeted round, independent and cached',async()=>{
 let visualCalls=0,extractCalls=0;const env={AI_API_KEY:'test',AI_BASE_URL:'https://test.example/v1',AI_MODEL:'model-1'};
 const si=doc('SHIPPING INSTRUCTIONS'),bl=doc('BILL OF LADING');si.pages[0].imageId='raster';
 const fetcher=async(url,opts)=>{const data=JSON.parse(opts.body),system=data.messages[0].content,input=JSON.parse(data.messages[1].content[0].text);let result;
  if(system.includes('BL_COMPARISON requires'))result={category:'BL_COMPARISON',quote:'Please check the draft BL against the SI.',reason:'Explicit request',needsReview:false};
  else {result=localExtract(input);delete result.provider;if(system.includes('Reconsider only')){visualCalls++;assert.equal(input.name,si.name)}else {extractCalls++;if(input.name===si.name)result.fields.gross_weight_kg={raw:'misread',quote:'misread',page:1,status:'OK'}}}
  return Response.json({choices:[{message:{content:JSON.stringify(result)}}]})};
 let c=await runPipeline(base(),[si,bl],env,{fetcher,getPageImage:async()=> 'data:image/png;base64,dGVzdA=='});assert.equal(visualCalls,1);assert.equal(extractCalls,2);assert.equal(c.fields.gross_weight_kg.comparison,'MATCH');
 c=await runPipeline(c,[si,bl],env,{fetcher,getPageImage:async()=> 'data:image/png;base64,dGVzdA=='});assert.equal(visualCalls,1);assert.equal(extractCalls,2)
});
test('net-weight quotes cannot validate a gross-weight extraction',()=>{const si=doc('SHIPPING INSTRUCTIONS'),bl=doc('BILL OF LADING');const a={...si,...localExtract(si)},b={...bl,...localExtract(bl)};a.fields.gross_weight_kg.quote='Net weight: 22000 KG';a.pages[0].text+='\nNet weight: 22000 KG';assert.equal(compareDocuments(a,b).gross_weight_kg.comparison,null)});
test('rechecking unchanged evidence retains reviewed differences',async()=>{const docs=[doc('SHIPPING INSTRUCTIONS'),doc('BILL OF LADING','4')];let c=await runPipeline(base(),docs);c=reviewAction(c,'verify',{field:'container_count'});c=await runPipeline(c,docs);assert.equal(c.fields.container_count.verified,true);assert.equal(c.fields.container_count.comparison,'MISMATCH')});
