import React,{useState,useEffect,useRef} from 'react';
import {motion,AnimatePresence,useReducedMotion} from 'motion/react';
import * as Dialog from '@radix-ui/react-dialog';
import * as Tabs from '@radix-ui/react-tabs';
import {X,ChevronDown,ArrowRight,FileText,Check,LoaderCircle} from 'lucide-react';
export const Button=({children,primary=false,busy=false,className='',...props})=><motion.button whileTap={{scale:.98}} className={`btn ${primary?'primary':''} ${className}`} {...props} disabled={props.disabled||busy}>{busy&&<LoaderCircle className="spin" size={17}/>} {children}</motion.button>;
export function Fold({title,children,defaultOpen=false}){const [open,setOpen]=useState(defaultOpen),reduce=useReducedMotion(),id=React.useId();return <div className="fold"><button className="fold-trigger" aria-expanded={open} aria-controls={id} onClick={()=>setOpen(!open)}><motion.span animate={{rotate:open?180:0}}><ChevronDown size={16}/></motion.span>{title}</button><AnimatePresence initial={false}>{open&&<motion.div id={id} initial={{height:reduce?'auto':0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:reduce?'auto':0,opacity:0}} transition={{duration:.18}} className="fold-content"><div>{children}</div></motion.div>}</AnimatePresence></div>}
export function Segments({value,onChange,items,label}){const id=React.useId();return <Tabs.Root value={value} onValueChange={onChange}><Tabs.List className="segments" aria-label={label}>{items.map(item=><Tabs.Trigger key={item.value} className="segment" value={item.value}>{value===item.value&&<motion.span className="segment-active" layoutId={id} transition={{type:'spring',bounce:.12,duration:.28}}/>}<span>{item.label}{item.count!==undefined&&<b>{item.count}</b>}</span></Tabs.Trigger>)}</Tabs.List></Tabs.Root>}
export function Modal({title,description,open,onClose,children,wide=false,drawer=false}){const previous=useRef(document.activeElement);return <Dialog.Root open={open} onOpenChange={v=>!v&&onClose()}><AnimatePresence>{open&&<Dialog.Portal forceMount><Dialog.Overlay asChild><motion.div className="dialog-overlay" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}/></Dialog.Overlay><Dialog.Content forceMount asChild onCloseAutoFocus={e=>{e.preventDefault();const target=previous.current;if(target?.isConnected)target.focus();else document.querySelector('main h1')?.focus()}}><motion.div className={`dialog-box ${wide?'wide':''} ${drawer?'drawer':''}`} initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} exit={{opacity:0,y:8}} transition={{duration:.17}}><div className="dialog-heading"><Dialog.Title>{title}</Dialog.Title><Dialog.Close asChild><button className="icon-btn" aria-label="Close dialog"><X size={18}/></button></Dialog.Close></div><Dialog.Description className="dialog-description">{description||'Review the information below.'}</Dialog.Description>{children}</motion.div></Dialog.Content></Dialog.Portal>}</AnimatePresence></Dialog.Root>}
export function Empty({title,body,children}){return <div className="empty new-empty"><span className="empty-icon"><FileText size={26}/></span><h2>{title}</h2><p>{body}</p>{children}</div>}
export function SaveFooter({onCancel,busy=false,label='Save decision & recheck',disabled=false}){return <div className="modal-actions"><Button onClick={onCancel}>Cancel</Button><Button primary busy={busy} type="submit" disabled={disabled}>{label}<ArrowRight size={16}/></Button></div>}
export function CheckLine({children,done}){return <div className="check-line"><span className={done?'green':'muted'}>{done?<Check size={18}/>:<LoaderCircle size={18}/>}</span>{children}</div>}
export class ErrorBoundary extends React.Component{state={error:null};static getDerivedStateFromError(error){return {error}}render(){return this.state.error?<div className="recovery"><h1>This page couldn’t load.</h1><p>Your saved records are still on this device.</p><button className="btn primary" onClick={()=>{location.hash='inbox';location.reload()}}>Return to workspace</button></div>:this.props.children}}
