import {confirmedFormats} from '../engine/format-choice.js';
import {applySourceProfile} from '../engine/source-profile.js';
import React,{useState} from 'react';
import {Button,Fold,Modal,SaveFooter} from './components.jsx';
import {api,cloudFile,processCase,uploadFile} from './api.js';
import {readDocument,releaseReader} from './reader.js';
import {toast} from 'sonner';
export function LiveCasePanel({record,batch,onUpdate}){
 const current=(record.docs||[]).map(applySourceProfile),all=[...(batch?.files||[]),...(record.supportFiles||[])].filter((v,i,a)=>!v.name.endsWith('.json')&&a.findIndex(f=>f.id===v.id)===i);
 const [selected,setSelected]=useState(current.map(d=>d.id)),[profiles,setProfiles]=useState(Object.fromEntries(current.map(d=>[d.id,d.numberProfile||'unset']))),[notes,setNotes]=useState(Object.fromEntries(current.map(d=>[d.id,d.profileEvidence||'']))),[busy,setBusy]=useState(false),[progress,setProgress]=useState(''),[error,setError]=useState('');
 async function run(){setBusy(true);setError('');try{const docs=[];for(const id of selected){const cached=current.find(d=>d.id===id&&d.pages?.length);let doc=cached||await readDocument(all.find(f=>f.id===id),setProgress);const profile=profiles[id]||'unset';docs.push(...confirmedFormats([doc],{[id]:{profile,note:notes[id]||''}}))}setProgress('Checking fields and preparing results…');const updated=await processCase(record,docs,{keepCategory:record.classification?.provider==='human',retry:!!record.processingError});onUpdate(updated);toast.success('Processing result saved.')}catch(e){setError(e.message)}finally{await releaseReader();setBusy(false);setProgress('')}}
 return <Fold title={record.pipeline?'Processing & original files':'Process these documents'} defaultOpen={!record.pipeline||!!record.processingError}>
 <p className="caption">{record.pipeline?.provider==='api'?'AI-assisted extraction':'Local rule-based extraction · AI API not configured'}. Original files and decisions are saved to your private workspace.</p>
 {record.processingDetail&&<p role="alert" className="form-error">{record.processingDetail}</p>}
 {!all.length&&<p>No attachments linked yet. Add the SI and BL as supporting files.</p>}
 {all.map(f=><div className="live-file-row" key={f.id}><label><input type="checkbox" checked={selected.includes(f.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,f.id]:s.filter(x=>x!==f.id))}/>{f.name}</label><a href={'/api/files/'+encodeURIComponent(f.id)} download>Original</a><select aria-label={'Number format for '+f.name} value={profiles[f.id]||'unset'} onChange={e=>setProfiles(s=>({...s,[f.id]:e.target.value}))}><option value="unset">Number format unknown</option><option value="en_comma">Comma groups · decimal point</option><option value="de_dot">Point groups · decimal comma</option></select>{profiles[f.id]&&profiles[f.id]!=='unset'&&<input aria-label={'Format evidence for '+f.name} value={notes[f.id]||''} onChange={e=>setNotes(s=>({...s,[f.id]:e.target.value}))} placeholder="Source location or sender confirmation for this file"/>}</div>)}

 <div className="flex wrap"><Button primary busy={busy} onClick={run} disabled={record.processingError&&record.retries>=1}>{record.pipeline?'Recheck selected sources':'Process selected sources'}</Button><label className="btn">Add source<input hidden type="file" accept=".pdf,.png,.jpg,.jpeg,.txt,.docx,.xlsx" onChange={async e=>{const f=e.target.files[0];if(!f)return;setBusy(true);try{const meta=await uploadFile(f);const data=await api('/cases/'+encodeURIComponent(record.id)+'/actions',{method:'POST',body:JSON.stringify({revision:record.revision,action:'support',payload:{file:meta}})});onUpdate(data);setSelected(s=>[...s,meta.id]);toast.success('Source saved. Select the intended files and recheck.')}catch(e){setError(e.message)}finally{setBusy(false);e.target.value=''}}}/></label></div>
 {progress&&<p role="status">{progress}</p>}{error&&<p role="alert" className="form-error">{error}</p>}
 {record.pipeline&&<p className="caption">{record.pipeline.status} · {record.pipeline.rules||'Rules pending'} · {record.pipeline.rereads||0} targeted rereads</p>}
 </Fold>
}
export function LiveResolution({record,field,close,apply}){
 const f=record.fields[field],[siValue,setSI]=useState(f.si||''),[blValue,setBL]=useState(f.bl||''),[decision,setDecision]=useState(''),[note,setNote]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 return <Modal open title="Record an evidence-backed decision" description="Check both original files. This decision applies only to this case." onClose={close}><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{await apply({siValue,blValue,decision,note});close()}catch(e){setError(e.message);setBusy(false)}}}><label className="field-label">SI value from the source<input className="full-width" value={siValue} onChange={e=>setSI(e.target.value)}/></label><label className="field-label">BL value from the source<input className="full-width" value={blValue} onChange={e=>setBL(e.target.value)}/></label><label className="field-label">Confirmed result<select className="full-width" required value={decision} onChange={e=>setDecision(e.target.value)}><option value="">Choose only if the evidence is sufficient</option><option value="MATCH">Same within the field comparison scope</option><option value="MISMATCH">Different — retain the difference</option></select></label><label className="field-label">Document, page and supporting fact<textarea required minLength={8} value={note} onChange={e=>setNote(e.target.value)}/></label>{error&&<p role="alert" className="form-error">{error}</p>}<SaveFooter busy={busy} onCancel={close}/></form></Modal>
}

export function LiveNumberFormat({record,close,onUpdate}){
 const docs=(record.docs||[]).map(applySourceProfile),paired=docs.filter(d=>[record.pair?.si,record.pair?.bl].includes(d.id));
 const [choices,setChoices]=useState(Object.fromEntries(paired.map(d=>[d.id,{profile:d.numberProfile||'unset',note:d.profileEvidence||''}]))),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const change=(id,key,value)=>setChoices(old=>({...old,[id]:{...old[id],[key]:value}}));
 return <Modal open title="Confirm each document’s number format" description="Use the original or sender confirmation. Each choice applies only to this document’s weight; unknown formats stay unresolved." onClose={close}><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{
  if(!Object.values(choices).some(c=>c.profile!=='unset'))throw Error('Confirm at least one source format, or leave this issue unresolved.');
  const updated=await processCase(record,confirmedFormats(docs,choices),{keepCategory:true});onUpdate(updated);close();toast.success('Formats recorded. Comparison recalculated from the sources.');
 }catch(e){setError(e.message);setBusy(false)}}}>
 {paired.map(d=><div key={d.id} className="field-label"><strong>{d.side?.toUpperCase()} · {d.name}</strong><p>{d.fields?.gross_weight_kg?.quote||'Open the original to check the weight.'}</p><a href={'/api/files/'+encodeURIComponent(d.id)} download>Open original</a><select aria-label={'Weight number format for '+d.name} value={choices[d.id].profile} onChange={e=>change(d.id,'profile',e.target.value)}><option value="unset">Still unknown</option><option value="en_comma">Decimal point · example 1,234.56</option><option value="de_dot">Decimal comma · example 1.234,56</option></select>{choices[d.id].profile!=='unset'&&<input required minLength={8} aria-label={'Evidence for '+d.name} placeholder="Page, format statement or sender confirmation" value={choices[d.id].note} onChange={e=>change(d.id,'note',e.target.value)}/>}</div>)}
 {error&&<p role="alert" className="form-error">{error}</p>}<SaveFooter busy={busy} onCancel={close}/></form></Modal>
}
