import React,{useState} from 'react';
import {Button,Fold,Modal,SaveFooter} from './components.jsx';
import {api,cloudFile,processCase,uploadFile} from './api.js';
import {readDocument,releaseReader} from './reader.js';
import {toast} from 'sonner';
export function LiveCasePanel({record,batch,onUpdate}){
 const current=record.docs||[],all=[...(batch?.files||[]),...(record.supportFiles||[])].filter((v,i,a)=>!v.name.endsWith('.json')&&a.findIndex(f=>f.id===v.id)===i);
 const [selected,setSelected]=useState(current.map(d=>d.id)),[profiles,setProfiles]=useState(Object.fromEntries(current.map(d=>[d.id,d.numberProfile||'unset']))),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[progress,setProgress]=useState(''),[error,setError]=useState('');
 async function run(){setBusy(true);setError('');try{const docs=[];for(const id of selected){const cached=current.find(d=>d.id===id&&d.pages?.length);let doc=cached||await readDocument(all.find(f=>f.id===id),setProgress);const profile=profiles[id]||'unset';if(profile!=='unset'&&!note.trim()&&!doc.profileEvidence)throw Error('Record the source specification supporting this number format.');docs.push({...doc,numberProfile:profile,profileEvidence:note||doc.profileEvidence})}setProgress('Checking fields and preparing results…');const updated=await processCase(record,docs,{keepCategory:record.classification?.provider==='human',retry:!!record.processingError});onUpdate(updated);toast.success('Processing result saved.')}catch(e){setError(e.message)}finally{await releaseReader();setBusy(false);setProgress('')}}
 return <Fold title={record.pipeline?'Processing & original files':'Process these documents'} defaultOpen={!record.pipeline||!!record.processingError}>
 <p className="caption">{record.pipeline?.provider==='api'?'AI-assisted extraction':'Local rule-based extraction · AI API not configured'}. Original files and decisions are saved to your private workspace.</p>
 {record.processingDetail&&<p role="alert" className="form-error">{record.processingDetail}</p>}
 {!all.length&&<p>No attachments linked yet. Add the SI and BL as supporting files.</p>}
 {all.map(f=><div className="live-file-row" key={f.id}><label><input type="checkbox" checked={selected.includes(f.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,f.id]:s.filter(x=>x!==f.id))}/>{f.name}</label><a href={'/api/files/'+encodeURIComponent(f.id)} download>Original</a><select aria-label={'Number format for '+f.name} value={profiles[f.id]||'unset'} onChange={e=>setProfiles(s=>({...s,[f.id]:e.target.value}))}><option value="unset">Number format unknown</option><option value="en_comma">Comma groups · decimal point</option></select></div>)}
 {Object.values(profiles).some(p=>p!=='unset')&&<label className="field-label">Number-format evidence<input className="full-width" value={note} onChange={e=>setNote(e.target.value)} placeholder="Document specification or sender confirmation"/></label>}
 <div className="flex wrap"><Button primary busy={busy} onClick={run} disabled={record.processingError&&record.retries>=1}>{record.pipeline?'Recheck selected sources':'Process selected sources'}</Button><label className="btn">Add source<input hidden type="file" accept=".pdf,.png,.jpg,.jpeg,.txt,.docx,.xlsx" onChange={async e=>{const f=e.target.files[0];if(!f)return;setBusy(true);try{const meta=await uploadFile(f);const data=await api('/cases/'+encodeURIComponent(record.id)+'/actions',{method:'POST',body:JSON.stringify({revision:record.revision,action:'support',payload:{file:meta}})});onUpdate(data);setSelected(s=>[...s,meta.id]);toast.success('Source saved. Select the intended files and recheck.')}catch(e){setError(e.message)}finally{setBusy(false);e.target.value=''}}}/></label></div>
 {progress&&<p role="status">{progress}</p>}{error&&<p role="alert" className="form-error">{error}</p>}
 {record.pipeline&&<p className="caption">{record.pipeline.status} · {record.pipeline.rules||'Rules pending'} · {record.pipeline.rereads||0} targeted rereads</p>}
 </Fold>
}
export function LiveResolution({record,field,close,apply}){
 const f=record.fields[field],[siValue,setSI]=useState(f.si||''),[blValue,setBL]=useState(f.bl||''),[decision,setDecision]=useState(''),[note,setNote]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 return <Modal open title="Record an evidence-backed decision" description="Check both original files. This decision applies only to this case." onClose={close}><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{await apply({siValue,blValue,decision,note});close()}catch(e){setError(e.message);setBusy(false)}}}><label className="field-label">SI value from the source<input className="full-width" value={siValue} onChange={e=>setSI(e.target.value)}/></label><label className="field-label">BL value from the source<input className="full-width" value={blValue} onChange={e=>setBL(e.target.value)}/></label><label className="field-label">Confirmed result<select className="full-width" required value={decision} onChange={e=>setDecision(e.target.value)}><option value="">Choose only if the evidence is sufficient</option><option value="MATCH">Same within the field comparison scope</option><option value="MISMATCH">Different — retain the difference</option></select></label><label className="field-label">Document, page and supporting fact<textarea required minLength={8} value={note} onChange={e=>setNote(e.target.value)}/></label>{error&&<p role="alert" className="form-error">{error}</p>}<SaveFooter busy={busy} onCancel={close}/></form></Modal>
}
