import {FIELD_KEYS,LABELS,makeCases} from './fixtures.js';
export {FIELD_KEYS,LABELS};
export const CATEGORIES={BL_COMPARISON:'BL comparison',SI_REQUEST:'SI request',INVOICE_QUERY:'Invoice query',GENERAL:'General',SPAM:'Spam'};
export const countFields=c=>({match:Object.values(c.fields||{}).filter(f=>f.comparison==='MATCH').length,diff:Object.values(c.fields||{}).filter(f=>f.comparison==='MISMATCH').length,unresolved:Object.values(c.fields||{}).filter(f=>f.comparison===null).length});
export const pending=c=>FIELD_KEYS.filter(k=>c.fields?.[k]&&(c.fields[k].comparison===null||c.fields[k].comparison==='MISMATCH'&&!c.fields[k].verified));
export function mode(c){if(c.processing)return 'processing';if(c.processingError||c.docIssue||c.pairIssue||c.classificationPending)return 'needs';if(c.category!=='BL_COMPARISON')return 'complete';return pending(c).length?'needs':'complete'}
export function issue(c,k){return c.processingError||c.docIssue||(c.pairIssue?'pairing':null)||(c.fields[k].comparison==='MATCH'?'match':c.fields[k].comparison==='MISMATCH'?'mismatch':c.fields[k].reason)||'evidence_not_located'}
export const ISSUE={
 missing_value:{title:'SI is missing this value',body:'Add source information before comparing this field.',label:'Add supporting material',action:'support'},
 missing_si:{title:'Add the missing SI',body:'This case needs one SI and one BL.',label:'Upload SI',action:'support'},
 missing_bl:{title:'Add the missing BL',body:'The SI is ready. Add its matching draft BL.',label:'Upload BL',action:'support'},
 wrong_type:{title:'This attachment is an invoice',body:'A draft BL is required for this booking.',label:'Upload correct BL',action:'support'},
 scan_illegible:{title:'This scan is still unreadable',body:'One reread did not resolve it. Add a clearer source.',label:'Upload clearer file',action:'support'},
 separator_ambiguous:{title:'What does 22.000 MT mean?',body:'Confirm the source’s number format before choosing.',label:'Choose interpretation',action:'resolve'},
 alias_collision:{title:'Which Portland is this?',body:'Use the country or a verified location code.',label:'Choose location',action:'resolve'},
 entity_identity:{title:'Are these the same company?',body:'Confirm with an address, identifier or business record.',label:'Review company evidence',action:'resolve'},
 extraction_incomplete:{title:'Check the extracted value',body:'The extracted count is 8. The sample original shows 3.',label:'Correct extracted value',action:'resolve'},
 evidence_not_located:{title:'Find this field in the original',body:'We could not locate it. Review both full documents.',label:'Record manual finding',action:'resolve'},
 port_name_code_conflict:{title:'The port name and code disagree',body:'Confirm the intended location from the source.',label:'Confirm location',action:'resolve'},
 alias_not_found:{title:'Confirm this port’s location',body:'Matching names do not resolve a location missing from the lookup table.',label:'Provide location evidence',action:'resolve'},
 invalid_container_count:{title:'Is the container count really 0?',body:'Both documents say 0. Ask for corrected information.',label:'Add corrected information',action:'support'},
 service_timeout:{title:'We couldn’t read this file',body:'Retry the failed reading stage once.',label:'Retry failed stage',action:'retry'},
 unsupported_format:{title:'We can’t open this format',body:'Add a PDF, image or supported document.',label:'Upload supported file',action:'support'},
 pairing:{title:'Choose the document pair',body:'Select one SI and one BL for this booking.',label:'Choose documents',action:'pair'},
 mismatch:{title:'These values don’t match',body:'Check both sources, then record that you reviewed the difference.',label:'Record verified difference',action:'verify'},
 match:{title:'These values agree',body:'No action is needed for this field.',label:'Next case',action:'next'},
};
export function finding(c){if(c.processing)return 'Processing sample documents';if(c.classificationPending)return 'Confirm the email request';if(c.processingError)return c.retries?'Retry limit reached':ISSUE[c.processingError]?.title||'Processing failed';if(c.docIssue)return ISSUE[c.docIssue]?.title;if(c.pairIssue)return c.multiple?'Multiple shipments to organize':'Multiple SI versions';if(c.category!=='BL_COMPARISON')return CATEGORIES[c.category]+' · no comparison';const n=countFields(c);if(n.diff&&n.unresolved)return `${n.diff} difference · ${n.unresolved} unresolved`;if(n.unresolved)return ISSUE[issue(c,pending(c)[0])]?.title||'Needs review';if(n.diff)return `${n.diff} difference${n.diff>1?'s':''}${mode(c)==='complete'?' · reviewed':''}`;return '7 fields matched'}
export function nextAction(c){if(c.processing)return 'View progress';if(c.classificationPending)return 'Review email';if(c.pairIssue)return 'Choose documents';if(mode(c)==='complete')return 'View result';if(c.retries)return 'Review failed stage';if(!c.docIssue&&!c.processingError&&pending(c).length>1)return `Handle ${pending(c).length} issues`;return ISSUE[issue(c,pending(c)[0]||'shipper')]?.label||'Review case'}
export const caseRoute=c=>c.processing?'progress':c.classificationPending||c.category!=='BL_COMPARISON'?`email/${c.id}`:c.pairIssue?`pair/${c.id}`:`review/${c.id}`;
export const sourceValue=(c,side,k)=>c.fields[k][side==='si'?'sourceSI':'sourceBL']??c.fields[k][side];
export function sourceText(c,side){return `${side==='si'?'SHIPPING INSTRUCTIONS':'DRAFT BILL OF LADING'}\n\n${c.company}\nBooking reference: ${c.booking}\n\n${FIELD_KEYS.map(k=>`${LABELS[k]}: ${sourceValue(c,side,k)}`).join('\n')}\n\nPreset source for interface demonstration.`}
export function documents(c){const base=side=>({id:`${side}-${c.id}-original`,side,name:`${side.toUpperCase()}_${c.id}_v1.txt`,booking:c.booking,date:'12 Sep',text:sourceText(c,side),sample:true});const docs=[];if(c.docIssue!=='missing_si')docs.push(base('si'));if(!['missing_bl','wrong_type'].includes(c.docIssue))docs.push({...base('bl'),id:'bl-current',date:'14 Sep'});if(c.type==='pairing'){docs.push({...base('si'),id:'si-revision',name:`SI_${c.id}_revision.txt`,date:'14 Sep'});docs.push({...base('bl'),id:'bl-other',name:'BL_BK-9902_other.txt',booking:'BK-9902',disabled:true})}return docs}
export function initialCases(){return makeCases().map(c=>({...c,demo:true,batchId:'demo',received:'2026-09-20T10:14:00',deferred:false,supportFiles:[],docs:documents(c)}))}
export function initialState(){return {version:3,cases:initialCases(),activeWorkspace:'demo',settings:{motion:true,density:'comfortable'},batches:[{id:'demo',name:'Example batch',demo:true,count:23,created:'2026-09-20T10:14:00',status:'ready'}],job:null}}
export function loadState(){try{const raw=localStorage.getItem('verity-workspace-v3');if(raw){const s=JSON.parse(raw);if(s.version===3&&Array.isArray(s.cases)&&Array.isArray(s.batches))return s}const v1=JSON.parse(localStorage.getItem('verity-demo-v1')||'null');if(Array.isArray(v1)&&v1.length===23){const s=initialState();s.cases=v1.map(c=>({...c,demo:true,batchId:'demo',received:'2026-09-20T10:14:00',supportFiles:[],docs:documents(c)}));return s}}catch{}return initialState()}
const audit=(c,title,detail)=>{c.history.unshift({title,detail,at:new Date().toISOString()});c.updated=new Date().toISOString()};
const snapshot=c=>{c.sourceVersions||=[];c.sourceVersions.push({version:c.version,fields:structuredClone(c.fields),docs:structuredClone(c.docs||[])});c.version++};
function recheck(c){for(const f of Object.values(c.fields))if(f.reason==='comparison_paused'){f.comparison=f.si===f.bl?'MATCH':'MISMATCH';f.kind=null;f.reason=null}c.deferred=false}
const PORTS=['SGSIN','MYPKG','USLAX','USPDX','AUPTJ'];
export function updateCase(original,action,p={}){
 const c=structuredClone(original),k=p.field||'gross_weight_kg',f=c.fields[k],why=f?issue(c,k):(c.processingError||c.docIssue);
 if(action==='verify'){if(f.comparison!=='MISMATCH')throw Error('Only an established difference can be verified.');f.verified=true;c.deferred=false;audit(c,'Difference verified',`${LABELS[k]}: SI ${f.si} / BL ${f.bl}. The result remains MISMATCH.`)}
 else if(action==='defer'){c.deferred=true;audit(c,'Left unresolved',p.note?.trim()||'No new evidence is available. Existing findings retained.')}
 else if(action==='retry'){if(c.processingError!=='service_timeout'||c.retries>=1)throw Error('No retry remains for this stage.');c.retries=1;audit(c,'Reading stage retried','The preset retry returned the same timeout. No comparison result was inferred.')}
 else if(action==='pair'){const si=c.docs.find(d=>d.id===p.si&&d.side==='si'),bl=c.docs.find(d=>d.id===p.bl&&d.side==='bl');if(!si||!bl||si.disabled||bl.disabled||si.booking!==bl.booking||si.booking!==c.booking)throw Error('Select an SI and BL belonging to this booking.');if(c.docIssue||c.processingError)throw Error('Resolve the missing or unreadable document first.');snapshot(c);c.pair={si:p.si,bl:p.bl};c.pairIssue=false;recheck(c);audit(c,'Document pair selected',`${si.name} + ${bl.name}. ${c.demo?'Preset fields compared.':'Pair confirmed for review.'}`)}
 else if(action==='multiple'){c.multiple=true;c.deferred=true;audit(c,'Multiple shipments flagged','Pairing remains unresolved until the materials are separated.')}
 else if(action==='support'){if(!p.file?.id)throw Error('Choose a file first.');c.supportFiles.push(p.file);audit(c,'Supporting material added',`${p.file.name}. Awaiting source review; uploading does not resolve this issue.`)}
 else if(action==='sample-support'){
  if(!c.demo)throw Error('Example recovery cannot change imported records.');snapshot(c);
  if(c.docIssue){c.docIssue=null;recheck(c);c.docs=documents(c)}else if(c.processingError==='unsupported_format'){c.processingError=null;recheck(c);c.docs=documents(c)}else{const val=why==='invalid_container_count'?'3':'235,550 KG';f.si=val;f.sourceSI=val;f.comparison=val===f.bl?'MATCH':'MISMATCH';f.kind=null;f.reason=null;f.verified=false;c.docs=documents(c)}c.deferred=false;audit(c,'Example replacement applied',`${LABELS[k]}: sample material supplied and affected values rechecked. Earlier sources retained.`)
 }
 else if(action==='resolve'){
  const note=p.note?.trim();if(!note||note.length<8)throw Error('Add the source location and the fact supporting your decision.');
  let si=f.si,comparison=null;
  if(why==='separator_ambiguous'){if(!['22000','22000000'].includes(p.value))throw Error('Choose a supported number interpretation.');si=Number(p.value).toLocaleString('en-US')+' kg';comparison=p.value==='22000'?'MATCH':'MISMATCH'}
  else if(why==='alias_collision'){if(!['USPDX','AUPTJ'].includes(p.value))throw Error('Choose the location supported by the source.');si=`Portland (${p.value})`;comparison=p.value==='USPDX'?'MATCH':'MISMATCH'}
  else if(why==='entity_identity'){if(!['same','different'].includes(p.value))throw Error('Choose same or different only with evidence.');comparison=p.value==='same'?'MATCH':'MISMATCH';f.identityDecision=p.value}
  else if(why==='extraction_incomplete'){if(!/^\d+$/.test(p.value)||Number(p.value)<1)throw Error('Enter a positive whole count.');if(c.demo&&p.value!==f.sourceSI)throw Error('The sample source shows 3. Use the source value.');si=p.value;comparison=si===f.bl?'MATCH':'MISMATCH'}
  else if(why==='evidence_not_located'){si=p.value?.trim();if(!si)throw Error('Transcribe the complete source value.');comparison=si.toLowerCase()===f.bl.toLowerCase()?'MATCH':'MISMATCH'}
  else if(['alias_not_found','port_name_code_conflict'].includes(why)){const code=p.value?.trim().toUpperCase(),bl=p.blCode?.trim().toUpperCase();if(!PORTS.includes(code))throw Error('This example supports SGSIN, MYPKG, USLAX, USPDX and AUPTJ.');if(why==='alias_not_found'&&!PORTS.includes(bl))throw Error('Confirm the BL location independently.');si=code;comparison=code===(why==='alias_not_found'?bl:'SGSIN')?'MATCH':'MISMATCH';f.normalizedBL=bl}
  else throw Error('This issue requires new source material, not an interpretation.');
  snapshot(c);f.sourceSI??=f.si;f.si=si;f.comparison=comparison;f.reason=null;f.kind=null;f.verified=false;f.evidenceNote=note;c.deferred=false;audit(c,'Evidence-backed decision saved',`${LABELS[k]}: ${comparison}. ${note}`)
 }
 else if(action==='classify'){
  if(!Object.keys(CATEGORIES).includes(p.category))throw Error('Choose an email category.');if(!p.note?.trim())throw Error('Record why the email belongs to this category.');c.category=p.category;c.classificationPending=false;c.deferred=false;if(p.category==='BL_COMPARISON'){c.docIssue='missing_si';c.fields=Object.fromEntries(FIELD_KEYS.map(k=>[k,{si:'Not extracted',bl:'Not extracted',comparison:null,kind:'UNREADABLE',reason:'comparison_paused'}]))}audit(c,'Email category confirmed',`${p.category}. ${p.note}`)
 }
 return c;
}
export function buildReport(cases,batches){return {report_type:'internal_review',generated_at:new Date().toISOString(),scope:'Document comparison; SI is a reference, not verified shipment truth.',contains_demo_data:cases.some(c=>c.demo),batches:batches.map(b=>({id:b.id,name:b.name,demo:b.demo,count:cases.filter(c=>c.batchId===b.id).length})),cases:cases.map(c=>({email_id:c.id,category:c.category,classification_pending:!!c.classificationPending,demo:!!c.demo,batch_id:c.batchId,progress:mode(c),deferred:!!c.deferred,finding:finding(c),version:c.version,fields:c.category==='BL_COMPARISON'?c.fields:null,document_issue:c.docIssue||null,pair_issue:!!c.pairIssue,processing_error:c.processingError||null,retries:c.retries||0,source_versions:c.sourceVersions||[],source_documents:c.docs||[],supporting_files:c.supportFiles||[],history:c.history}))}}
export function csvReport(cases){const cell=v=>{const text=String(v??'');return '"'+(/^[\s]*[=+@-]/.test(text)?"'":'')+text.replaceAll('"','""')+'"'};return [['Email ID','Company','Category','Progress','Finding','Demo'],...cases.map(c=>[c.id,c.company,c.category,mode(c),finding(c),c.demo?'Yes':'No'])].map(row=>row.map(cell).join(',')).join('\r\n')}
export function download(name,content,type='application/json'){const u=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),2000)}
export function exportReady(cases){return !cases.some(c=>c.demo||c.classificationPending||mode(c)!=='complete')}
export function importEmails(rows,batchId){const seen=new Set();return rows.map((e,i)=>{const id=String(e.email_id||e.id||`${batchId}-${i+1}`);if(seen.has(id))throw Error(`Duplicate email ID: ${id}`);seen.add(id);if(typeof e.subject!=='string'||typeof (e.body??e.content)!=='string')throw Error(`Email ${id} needs a subject and full body.`);return {id:`${batchId}/${id}`,emailId:id,company:typeof e.from==='string'?e.from: e.from?.email||'Imported email',category:'GENERAL',classificationPending:true,subject:e.subject,body:e.body??e.content,attachments:e.attachments||[],fields:{},demo:false,batchId,booking:id,version:1,supportFiles:[],docs:[],received:e.date||new Date().toISOString(),history:[{title:'Email imported',detail:'Original message retained. Classification and extraction have not run.',at:new Date().toISOString()}]}})}
